# =====================================================
# Performance & responsiveness
# =====================================================

repaint_delay 2
input_delay 0
sync_to_monitor yes

# Reduce unnecessary overhead
window_alert_on_bell no
enable_audio_bell no
