#!/usr/bin/env bash

set -euo pipefail

if command -v brew >/dev/null 2>&1; then
  brew install git ripgrep fd go lua-language-server stylua shfmt
  go install golang.org/x/tools/gopls@latest

  # Install Treesitter parsers
  ./scripts/parsers

elif command -v pacman >/dev/null 2>&1; then
  ./scripts/arch-install

else
  echo "Unsupported package manager"
  exit 1
fi
