#!/usr/bin/env bash

set -euo pipefail

if command -v brew >/dev/null 2>&1; then
  brew upgrade
elif command -v pacman >/dev/null 2>&1; then
  sudo pacman -Syu
fi

go install golang.org/x/tools/gopls@latest

if ! command -v stylua >/dev/null 2>&1; then
  if command -v cargo >/dev/null 2>&1; then
    cargo install stylua
  fi
fi
